### ISSUE TITLE
Desafio de Design - Andrey Leitão

### ISSUE THREAD

**Issue by suissa** [Webschool-io/be-mean#1]
Votação da arte final do Be MEAN!!

**Comment by suissa** [comment]
![andrey-leitao---bemean](https://cloud.githubusercontent.com/assets/75607/9671472/8f3488b6-5269-11e5-9705-87f826f0fddf.png)

**Comment by suissa** [comment]
![emersonlemos](https://cloud.githubusercontent.com/assets/75607/9671600/5d47b5d4-526a-11e5-9c53-1a788528de95.png)

**Comment by robsongajunior** [comment]
https://github.com/Webschool-io/be-mean-instagram/issues/1#issuecomment-137580788 +1

**Comment by suissa** [comment]
![guilherme diego](https://cloud.githubusercontent.com/assets/75607/9671613/7ab7c550-526a-11e5-804d-9ea533d26e08.jpg)

**Comment by dflima** [comment]
:+1:

**Comment by dflima** [comment]
+1 https://github.com/Webschool-io/be-mean-instagram/issues/1#issuecomment-137580788

**Comment by dflima** [comment]
+1 https://github.com/Webschool-io/be-mean-instagram/issues/1#issuecomment-137579783

**Comment by carlosjuchoa** [comment]
Muito bom !! no aguardo da abertura .. :)

**Comment by GabrielJMJ** [comment]
1

**Comment by EmersonLemos** [comment]
2

**Comment by LukSimoes** [comment]
2

**Comment by tabataruiz** [comment]
+1

**Comment by reginaldojunior** [comment]
+1

**Comment by vandercijr** [comment]
+1
