### ISSUE TITLE
Sobre a forma de entregar os exercícios!

### ISSUE THREAD

**Issue by ftonato** [Webschool-io/be-mean#124]
Considerando a quantidade de alunos, exercícios e de módulos, não seria mais interessante se fosse feito um _pr_ por módulo com todos os exercícios dentro de um diretório?

Dessa forma evitaria tantos _merge_ e não teria que perder tanto tempo!

//cc @suissa

**Comment by asfelix** [comment]
mas afinal @suissa , não basta colocar o link no EAD da aula em específico? Ou há mesmo a necessidade de fazer um PR

**Comment by angelorubin** [comment]
O acesso para enviar os exercícios (no dágora) é somente para quem pagou?

**Comment by ghost** [comment]
Uma idéia seria criar um time  para os alunos na organização  da webschool.io aqui no github e adicionar todos os alunos como membro, ai seria só dar commit e push!

Será que iria funcionar? @suissa 
:beers:

**Comment by suissa** [comment]
https://github.com/Webschool-io/be-mean-instagram-mongodb-excercises

**Comment by suissa** [comment]
Os exercícios SAO PARA TODOSSSS!!!
