### ISSUE TITLE
Tradução - Inglês - mongodb/theory-nosql.md

### ISSUE THREAD

**Issue by carlosmachel** [Webschool-io/be-mean#17]
Vou traduzir esse arquivo.

**Comment by osvaldoabel** [comment]
Até poderia adicionar uma pasta referente ao idioma,  dentro do módulo.
Exemplo: 
- Mongodb
  -  /en
  -  /pt-br

Etc. Desse modo , se alguém quiser traduzir para outro idioma fica mais fácil.

**Comment by carlosmachel** [comment]
Boa ideia. Então o @suissa adicionaria o conteúdo na pasta /pt-br e talvez a medida que novos idiomas sejam traduzidos, o primeiro que adicionar aquele idioma criaria a pasta.

**Comment by osvaldoabel** [comment]
@carlosmachel  , vai traduzir também o arquivo mongodb/theory.md , ou só o mongodb/theory-nosql.md ? é que, quero traduzir o mongodb/theory.md

**Comment by carlosmachel** [comment]
To traduzindo por enquanto apenas o theory-nosql.md mesmo.

**Comment by Pompeu** [comment]
nice :P

**Comment by suissa** [comment]
@Kanguanda to fazendo isso mesmo, separando por pastas!!

**Comment by suissa** [comment]
Agora ficou TOP https://github.com/Webschool-io/be-mean-instagram/tree/master/Apostila/module-mongodb

:tada:
