### ISSUE TITLE
Referenciar o site "HTTP Status Cats" ao falar de API

### ISSUE THREAD

**Issue by lcpereira-zz** [Webschool-io/be-mean#19]
Ao comentar dos status code de chamadas API, referenciar o site http://http.cat/ que curti bastante quando o @suissa nos mostrou no workshop Be MEAN :smile: .

**Comment by Pompeu** [comment]
KKK to rindo muito disso sou o jean mesmo hqhhehe

**Comment by felipeands** [comment]
kkkk que massa!

**Comment by suissa** [comment]
https://github.com/Webschool-io/be-mean-instagram/blob/master/Apostila/module-nodejs/http.md#cats-api
