### ISSUE TITLE
Tradução - Inglês - mongodb/installation.md

### ISSUE THREAD

**Issue by osvaldoabel** [Webschool-io/be-mean#20]
Tradução do arquivo mongodb/installation.md para o inglês.

**Comment by wbruno** [comment]
Já foi feito

https://github.com/Webschool-io/be-mean-instagram/blob/master/apostila/module-mongodb/installation.md

https://github.com/Webschool-io/be-mean-instagram/blob/master/apostila/module-mongodb/installation-EN.md
