### ISSUE TITLE
Qual a pasta correta para os exercícios?

### ISSUE THREAD

**Issue by asfelix** [Webschool-io/be-mean#216]
@suissa estou vendo que tem aluno colocando exercicios em tudo quanto é pasta e tu tá dando merge geral. Olha os exemplos:
https://github.com/Webschool-io/be-mean-instagram/tree/master/apostila/classes/mongodb/exercices
https://github.com/Webschool-io/be-mean-instagram/tree/master/apostila/classes/mongodb/exercises
https://github.com/Webschool-io/be-mean-instagram/tree/master/apostila/mongodb/exercises
https://github.com/Webschool-io/be-mean-instagram/tree/master/exercises

Não seria interessante estar em um local só? Eu segui o seu exemplo e mandei o meu para o mesmo local que tu criou o exemplo: https://github.com/Webschool-io/be-mean-instagram/blob/master/apostila/classes/mongodb/exercises/class-01-resolved-suissa-jean-nascimento.md

Se concordar, posso mover as outras que encontrei espalhadas por aí para um unico local, o que acha?

**Comment by ftonato** [comment]
Conforme mostra o segundo vídeo, a pasta correta é a [exercises](https://github.com/Webschool-io/be-mean-instagram/tree/master/apostila/classes/mongodb/exercises).

**Comment by ftonato** [comment]
Imagino que a pasta **exercises** que está na em [master](https://github.com/Webschool-io/be-mean-instagram/tree/master/exercises) não deveria existir. /cc @robsonfagundes 
Assim como o arquivo **class-01-resolved.md** que se encontra no [mesmo lugar](https://github.com/Webschool-io/be-mean-instagram/blob/master/class-01-resolved.md). /cc @Dariano

**Comment by robsonfagundes** [comment]
https://github.com/Webschool-io/be-mean-instagram/pull/323
vlw!

**Comment by ftonato** [comment]
@robsonfagundes :+1:

**Comment by suissa** [comment]
https://github.com/Webschool-io/be-mean-instagram-mongodb-excercises
