### ISSUE TITLE
Correção da palavra `easier` (inglês) no arquivo mongodb/installation-EN.md

### ISSUE THREAD

**Issue by osvaldoabel** [Webschool-io/be-mean#23]
Correção da palavra  **easier** (inglês) .
De **easyer** para **easier**

**Comment by ftonato** [comment]
Acho que seria interessante dizer em qual documento está esse erro :)

**Comment by osvaldoabel** [comment]
verdade :) 
Obrigado @ftonato

**Comment by ftonato** [comment]
:+1:

**Comment by suissa** [comment]
Pode ajeitar e dar um PR

**Comment by wbruno** [comment]
Foi corrigido já

https://github.com/Webschool-io/be-mean-instagram/blob/master/apostila/module-mongodb/installation-EN.md
