### ISSUE TITLE
Instalar Mongodb no Linux Mint

### ISSUE THREAD

**Issue by AndresGrams** [Webschool-io/be-mean#385]
Install Mongodb on Linux Mint Rebecca
09 MARCH 2015
I'm a noob when it comes down to Linux. So today got an issue installing MongoDB, I followed the default instructions but they didn't work. I got the following error:

W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/rebecca/mongodb-org/3.0/main/binary-amd64/Packages 404 Not Found

The problem here is that I use Linux Mint and the distro name (rebecca) is not supported. So the problem is in step 2 using the following command:

echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

You have to use the ubuntu distro name instead, so for Linux Mint Rebecca you change it to trusty:

echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

You can find what ubuntu version Mint is based on: http://www.linuxmint.com/oldreleases.php

Maybe one day this post can help that one other individual that has no clue what he's doing with linux.

**Comment by Adejair** [comment]
Opa, @C0D3R4 , tudo bem?

Eu instalei recentemento o mongodb no mint, ele já vem com um ppa que há o mongodb.

```

sudo apt-get install mongodb
```

Depois basta você rodar normalmente :+1:
