### ISSUE TITLE
Esta confusa a instalação no windows

### ISSUE THREAD

**Issue by angelorubin** [Webschool-io/be-mean#444]
Esta confusa a instalação do MongoDB no (ru)windows pelo tutorial do Pablo - https://pablojuancruz.wordpress.com/2014/09/03/configurando-ambiente-mongodb-no-windows

Na parte onde ele fala sobre criar as pastas, não se entende bem onde se deve criar, portanto eu fiz desta forma e funcionou tranquilo:

1 - Baixar o binário no site do MongoDB para windows
2 - Criar uma pasta chamada mongodb na raiz do seu computador (C:\mongodb) 
3 - Após "dezipar" os arquivos binários baixados, pegue apenas a pasta bin e coloque-a dentro da pasta criada (C:\mongodb), ficará algo assim (C:\mongodb\bin)
4 - Na parte onde fala sobre criar a pasta data/db, esta deve ser criada na raiz do seu computador também, ou seja, (C:\data\db)
5 - O resto é só seguir como no tutorial mesmo que vai funcionar certinho

Espero que ajude alguém.

**Comment by suissa** [comment]
É soh vc arrumar e mandar um PR

**Comment by Pompeu** [comment]
como sugerido pelo @suissa  faça o PR.
bjs
