### ISSUE TITLE
Instalação mongodb para ubuntu

### ISSUE THREAD

**Issue by carlan** [Webschool-io/be-mean#46]
O arquivo de descrição de instalação não está indicando que a instalação está disponível somente para o ambiente 64-bits.

**Comment by carlan** [comment]
Descrição alterada e pr enviado.

**Comment by Marcelosilva10** [comment]
Boa noite, man uso o elementary, uma versão do Ubuntu também segue o link...

https://docs.mongodb.org/manual/tutorial/install-mongodb-on-linux/

**Comment by carlan** [comment]
@Marcelosilva10,

Valeu cara. Eu migrei para 64 bits e consegui fazer a instalação. Você tentou instalar conforme a documentação oficial ou a apostila do curso em um sistema 32 bits?

Via apt-get não rola por que o repositório de 32 bits está vazio. Por isso que queria chamar a atenção para isso. Perdi o maior tempão pra descobrir o problema.

Mais [aqui](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/).

**Comment by Marcelosilva10** [comment]
OK, tudo bem

**Comment by wbruno** [comment]
Alertado.

https://github.com/Webschool-io/be-mean-instagram/commit/3e7fd8a4a3acd8a3aacc5d008e66d371c5dd7db3
