### ISSUE TITLE
Link quebrado para o JSON do exercício 1

### ISSUE THREAD

**Issue by robsonbittencourt** [Webschool-io/be-mean#634]
O [exercício de import export da aula 1](https://github.com/Webschool-io/be-mean-instagram/blob/master/apostila/module-mongodb/export_import.md) está com o link para o [JSON de restaurantes](https://raw.githubusercontent.com/Webschool-io/be-mean-instagram/master/apostila/mongodb/data/restaurantes.json) quebrado.

**Comment by suissa** [comment]
É soh vc arrumar e mandar um PR

**Comment by robsonbittencourt** [comment]
Algum outro commit já arrumou o link. Valeu!
