### ISSUE TITLE
MongoDB - parte do William

### ISSUE THREAD

**Issue by suissa** [Webschool-io/be-mean#670]
@wbruno filhao escreve tua parte ai faz favor

**Comment by wbruno** [comment]
okay!

**Comment by DouglasHennrich** [comment]
@wbruno vc poderia melhorar a documentação sobre o [aggregation](https://github.com/Webschool-io/be-mean-instagram/blob/master/Apostila/module-mongodb/pt-br/aggregation.md) ?
Ontem fui dar uma estudada nisso e fiquei na mão ): tanto nos slides quanto na apostila, não está falando mt sobre o `aggregation`, está mt vago na apostila

valeus =)

**Comment by suissa** [comment]
Verdade man, tem como agilizar ai @wbruno ???
