### ISSUE TITLE
Aula 04 - NodeJS

### ISSUE THREAD

**Issue by DouglasHennrich** [Webschool-io/be-mean#683]
O professor @caiocutrim poderia add um `.md` contendo as perguntas dos exercícios que ele passa em vídeo também =)

A segunda parte do video, modulo FS, ficou extremamente ruim de ver os exercícios, embora esteja em 720p o youtube... a primeira parte que foi sobre Callback, ficou perfeito, bem nítido, não sei qq rolou na segunda parte, sobe FS

**Comment by suissa** [comment]
Exatamente!

**Comment by suissa** [comment]
Isso ai @caiocutrim

**Comment by DouglasHennrich** [comment]
@caiocutrim poderia brotar aí pra gente poder fechar a issue né?
E tu tbm poderia entrar no chat do be-mean no rocket, pq quis te passar essa issue pelo chat e nao te achei la =(

**Comment by suissa** [comment]
Waiting...

**Comment by caiocutrim** [comment]
Opaaa galerooo, valeu pelo feedback, vou subir as questões agora, eu tava meio doente esses dias :-1:

**Comment by caiocutrim** [comment]
Não foi passado os exercícios ainda dessa aula, vai ficar para a quinta aula, e vai ter um desafio. Só foi passado os exercícios da aula de callbacks

**Comment by DouglasHennrich** [comment]
vc passou em aula os exercícios, tanto que já tem nego, como eu, que já enviaram o exercício aehuaehuaeh mas valeu caio :+1:  e entra no chat do be-mean xD
