### ISSUE TITLE
http-get-localhost-querystring.js

### ISSUE THREAD

**Issue by araujobarret** [Webschool-io/be-mean#685]
Os código fornecido não roda, dá um erro na conexão.
Exemplo: 
events.js:142
throw er; // Unhandled 'error' event
^

Error: connect ECONNREFUSED 127.0.0.1:3000

Vi em alguns sites falando que precisa do http.request().
O código do exemplo da apostila está correto mesmo ou precisa de algo a mais?

**Comment by araujobarret** [comment]
tem que levantar um node separado com uma página de resposta...lol

**Comment by DouglasHennrich** [comment]
exatamente, tem que levantar o servidor primeiro, para dps fazer esse exercício... fecha a issue, se não tem mais dúvidas =)
