### ISSUE TITLE
Aula 04 NodeJS

### ISSUE THREAD

**Issue by DouglasHennrich** [Webschool-io/be-mean#695]
Fiquei meio em dúvida de como/o que fazer no [desafio aula 04](https://github.com/Webschool-io/be-mean-instagram/blob/master/Apostila/classes/nodejs/exercises/class-04.md).

é para usar express para fazer esse servidor estático? Usar só as bibliotecas `fs` `http` para criar esse servidor?

Acho que ficou mal explicado esse desafio, **OU** eu que nao entendi mesmo uhaeuheauahe

Sugiro também que o exercício descrito ali em cima, seja atribuído como "Parte 2", pois no próprio vídeo, já tem exercício da primeira parte do vídeo =)

Valeu

**Comment by suissa** [comment]
Apenas fs né @caiocutrim ??

**Comment by DouglasHennrich** [comment]
acho que tem que dar um assign nele ali do lado para ele ser "puxado" para essa issue
