### ISSUE TITLE
Exercício Aula 06 - Node.js

### ISSUE THREAD

**Issue by ednilsonamaral** [Webschool-io/be-mean#712]
@suissa no [exercício](https://github.com/Webschool-io/be-mean-instagram/blob/master/Apostila/classes/nodejs/exercises/class-06.md) da aula 6, na parte que vc mostra qual o padrão que ser feito o arquivo.MD, você repetiu um [exercício 3](https://github.com/Webschool-io/be-mean-instagram/blob/master/Apostila/classes/nodejs/exercises/class-05.md) da aula 5. Na lista de exercícios está de boa, só onde tu mostra o padrão que ficou repetido..

**Comment by DouglasHennrich** [comment]
Referente ao pull request #701 
já foi arrumado isso =)

**Comment by ednilsonamaral** [comment]
Suave então! Fechando issue! :)

**Comment by DouglasHennrich** [comment]
:+1:
