### ISSUE TITLE
Hangout sobre TypeScript

### ISSUE THREAD

**Issue by nicolastakashi** [Webschool-io/be-mean#741]
Apresentação sobre o TypeScript e suas vantagens e o impacto que ele tem no desenvolvimento de aplicações web.

Data proposta 16/03/2016 ás 20:00 PM horário de Brasilia.

**Comment by suissa** [comment]
SHOWW! Curto pra caraleo TS e eh FUNDAMENTAL os alunos do Be MEAN conhecerem pois futuramente UTILIZAREMOS SIM!!!!

**Comment by DouglasHennrich** [comment]
https://github.com/Webschool-io/be-mean-hangouts

Adiciona seu hangout lá =)

**Comment by wilsilva** [comment]
Show de bola!!
