### ISSUE TITLE
Correção da qualidade da aula de fylesystem

### ISSUE THREAD

**Issue by caiocutrim** [Webschool-io/be-mean#755]
Refatoração da aula de node de filesystem, uma solução imediata é ver as aulas anteriores de node, já tem 10 aulas completas, encontradas nesse link aqui: https://www.youtube.com/playlist?list=PL77JVjKTJT2i5lKXVqMibd9L0GueMSaLZ, o que passar disso é reeinvento de coisas, que na maioria dos casos não é tão ruim assim, mas neste supracitado é perca de tempo.

**Comment by suissa** [comment]
Ficou uma merda mesmo assim.
