### ISSUE TITLE
Finalizou o curso

### ISSUE THREAD

**Issue by joelvictoraluiz** [Webschool-io/be-mean#810]
Boa noite!

              Acabou o curso ou ainda faltam aulas?

Desde já agradeço pelo material de qualidade disponibilizado.

**Comment by alexsmonte** [comment]
Em q pese todas as tretas, esse curso nunca acabou é o comentario no meio dos cursos online :D

**Comment by suissa** [comment]
https://medium.com/@osuissa/be-mean-a-solucao-6d4c682d1140
